# Git sync
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client
    # access mode of the persistent volume
    accessMode: ReadWriteMany

  gitSync:
    enabled: true
    repo: https://github.com/wizelineacademy/Google-Africa-DEB
    branch: main
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "/session_06/session_06/exercises/airflow-gke/dags"


logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client
